name: CI - Build and Push UI Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push to ghcr.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actior}}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tages: |
            ghcr.io/${{ github.repository_owner }}/team-app-ui:latest
            ghcr.io/${{ github.repository_owner }}/team-app-ui:${{ github.sha }}