name: CI/CD - Build, Push, and Deploy UI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UI code
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/team-app-ui:${{ github.sha }}

      

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

   
      - name: Checkout Platform Config repo
        uses: actions/checkout@v4
        with:
          repository: hjali7/team-app-platform-config 
          path: platform-config 
          token: ${{ secrets.PLATFORM_CONFIG_TOKEN }} 

    
      - name: Update image tag in platform-config
        run: |
          cd platform-config
          
          # ساختن آدرس کامل ایمیج جدید با تگ SHA
          export NEW_IMAGE_URL="ghcr.io/${{ github.repository_owner }}/team-app-ui:${{ github.sha }}"
          
          # استفاده از yq برای آپدیت کردن فایل
          yq -i '(kind == "Deployment") .spec.template.spec.containers[0].image = strenv(NEW_IMAGE_URL)' base/03-frontend-deployment.yaml
          
          
          git config --global user.name "GitHub Actions (UI)"
          git config --global user.email "actions@github.com"
          
          
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to deploy."
          else
            git commit -m "feat(ui): update frontend image to ${{ github.sha }}"
            git push
          fi
